#!/bin/sh -xeu

ZI_DUMP_CSV="https://github.com/zapret-info/z-i/raw/0f69ad8852a79fa3ba3a9a788b8e2157cd1da9f7/dump.csv"
CURL_OPTS="--connect-timeout 15 --location"

is_nightly() {
    # Fixed version of nightly for clippy.
    echo "${TRAVIS_RUST_VERSION}" | grep -qe "^nightly"
}

is_nightly_for_clippy() {
    # Fixed version of nightly for clippy.
    echo "${TRAVIS_RUST_VERSION}" | grep -qe "^nightly-.*"
}

if [ "${1}" = "before_script" ]; then
    if is_nightly_for_clippy; then
        cargo "+${TRAVIS_RUST_VERSION}" install clippy --version "${CLIPPY_VERSION}" --force
    fi
elif [ "${1}" = "script" ]; then
    if is_nightly; then
        features="--features unstable"
    else
        features=""
    fi

    # Should go first, otherwise skeptic test will fail.
    cargo test --all ${features}
    cargo test --release --all ${features}

    if is_nightly_for_clippy; then
        cargo "+${TRAVIS_RUST_VERSION}" clippy --all --profile test ${features}
    fi

    cargo build --all ${features}

    cargo build --release --all ${features}

    curl $CURL_OPTS --output "./dump.csv" "${ZI_DUMP_CSV}"
    for build_type in "debug" "release"; do
        "./target/${build_type}/zicsv-tool" --input "./dump.csv" into-json --disable-pretty >/dev/null
    done
else
    printf "Unknown command: %s\n" "${1}" >&2
    exit 1
fi
